### ISSUE TITLE
Unknown runtime specified nvidia

### ISSUE THREAD

**Issue by sidhulyalkar** [bernardosabatinilab/sabatini-datajoint-pipeline#13]
- I have run into a problem configuring a new workstation to run the spike sorting worker. I have successfully installed nvidia-docker, have my cuda/gpu configured, and have installed the nvidia-container-runtimes and changed my docker/daemon.json file to point to the proper path (images attached). However, every time I attempt to up the worker, I do get an error Error response from daemon: Unknown runtime specified nvidia and if I check my default runtimes, runc is the default. There were some things I had to change given the new nvidia-containers and new drivers so I'm not sure if I missed something along the way. Any clues as to how to remedy the issue?

![Capture1](https://user-images.githubusercontent.com/19501777/230147845-b602e460-f25b-4d33-8ce9-71c603730e6b.PNG)

![Capture (2)](https://user-images.githubusercontent.com/19501777/230147882-e7e23a22-11ee-461c-aeee-78a4dc2f92aa.PNG)

![Capture4](https://user-images.githubusercontent.com/19501777/230147917-50859988-d550-4e87-b8ec-68d9dc877702.PNG)

![Capture3](https://user-images.githubusercontent.com/19501777/230147947-74f9e23e-5feb-4cad-9b73-00426b79cbd6.PNG)

![Capture2](https://user-images.githubusercontent.com/19501777/230148153-d74e6c7e-98cb-4015-b7d5-4c92d17678c0.PNG)

**Comment by jbwallace123** [comment]
Solved by removing runtime:nvidia in docker compose file [HERE](https://github.com/bernardosabatinilab/sabatini-datajoint-pipeline/blob/5d2079dcfd19750d72b7b7565b1ec16cead85c46/docker/spike_sorting_local_worker/dist/debian/docker-compose-spike_sorting_local_worker.yaml#L21)
